import { Employee, JobRequisition, LeaveRequest, AttendanceRecord, PayrollRun, PerformanceGoal, Course, SupportTicket, CompanyAnnouncement } from "./types";

export const initialEmployees: Employee[] = [
  {
    id: "EMP-001",
    name: "SMI Fahim",
    email: "fahim@workforcehub.com",
    avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=256&auto=format&fit=crop",
    role: "CEO & Managing Director",
    department: "Executive Committee",
    salary: 450000,
    joiningDate: "2020-01-15",
    status: "Active",
    skills: ["Strategic Leadership", "Enterprise Architecture", "Mergers & Acquisitions", "VC Relations"],
    certifications: ["Harvard AMP", "Insead Executive Leadership"],
    phone: "+880-1711-234567",
    bloodGroup: "O+",
    bankAccount: "1029384756102",
    bankName: "Standard Chartered Bank, Gulshan Branch",
    tin: "873918273645",
    emergencyContactName: "Tanvir Ahmed (Brother)",
    emergencyContactPhone: "+880-1819-998877",
    medicalBenefits: "Executive Gold Care Plan (Unlimited Coverage)",
    performanceRating: 5,
    leaveBalance: { casual: 10, sick: 14, earned: 24, maternity: 0 },
    promotions: [{ title: "Founding CEO", date: "2020-01-15" }],
    awards: ["ICT Pioneer Award 2024", "Outstanding Entrepreneur 2025"],
    disciplinaryActions: []
  },
  {
    id: "EMP-002",
    name: "Abrar Ishraq",
    email: "abrar.ishraq@workforcehub.com",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=256&auto=format&fit=crop",
    role: "HR Director",
    department: "Human Resources",
    salary: 220000,
    joiningDate: "2021-03-01",
    status: "Active",
    skills: ["Talent Strategy", "Bangladesh Labour Act", "SAP SuccessFactors", "Compensation & Benefits"],
    certifications: ["SHRM-SCP", "SADP (Bangladesh Law Certified)"],
    phone: "+880-1711-887766",
    bloodGroup: "A+",
    bankAccount: "5544332211990",
    bankName: "HSBC Bangladesh, Banani Branch",
    tin: "283940192837",
    emergencyContactName: "Sabrina Ishraq (Spouse)",
    emergencyContactPhone: "+880-1678-554433",
    medicalBenefits: "Premium Enterprise Health Insurance",
    performanceRating: 5,
    leaveBalance: { casual: 12, sick: 10, earned: 18, maternity: 0 },
    promotions: [
      { title: "Senior HR Manager", date: "2021-03-01" },
      { title: "HR Director", date: "2023-06-01" }
    ],
    awards: ["HR Leader of the Year 2024"],
    disciplinaryActions: []
  },
  {
    id: "EMP-003",
    name: "Suchana",
    email: "suchana@workforcehub.com",
    avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?q=80&w=256&auto=format&fit=crop",
    role: "Manager, HR",
    department: "Human Resources",
    salary: 140000,
    joiningDate: "2022-05-10",
    status: "Active",
    skills: ["Onboarding", "Conflict Resolution", "Performance Appraisals", "Workday"],
    certifications: ["PHR-i", "Workday Core HCM"],
    phone: "+880-1722-112233",
    bloodGroup: "B+",
    bankAccount: "9988776655443",
    bankName: "City Bank, Kawran Bazar Branch",
    tin: "556677889900",
    emergencyContactName: "Imtiaz Rahman (Father)",
    emergencyContactPhone: "+880-1911-334455",
    medicalBenefits: "Premium Enterprise Health Insurance",
    performanceRating: 4,
    leaveBalance: { casual: 8, sick: 12, earned: 15, maternity: 112 },
    promotions: [{ title: "Manager, HR", date: "2022-05-10" }],
    awards: ["Employee of the Month - March 2025"],
    disciplinaryActions: []
  },
  {
    id: "EMP-004",
    name: "Kiron Rahman",
    email: "kiron.rahman@workforcehub.com",
    avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?q=80&w=256&auto=format&fit=crop",
    role: "Asst Manager HR",
    department: "Human Resources",
    salary: 95000,
    joiningDate: "2023-01-15",
    status: "Active",
    skills: ["Employee Relations", "Recruitment Pipe", "Payroll Operations"],
    certifications: ["HR Fundamentals Certified"],
    phone: "+880-1733-445566",
    bloodGroup: "O+",
    bankAccount: "1122334455667",
    bankName: "Dutch-Bangla Bank, Mohakhali Branch",
    tin: "123498765432",
    emergencyContactName: "Asma Begum (Mother)",
    emergencyContactPhone: "+880-1552-667788",
    medicalBenefits: "Standard Corporate Health Shield",
    performanceRating: 4,
    leaveBalance: { casual: 9, sick: 11, earned: 12, maternity: 0 },
    promotions: [{ title: "Asst Manager HR", date: "2023-01-15" }],
    awards: ["Top Recruiter Award Q4 2025"],
    disciplinaryActions: []
  },
  {
    id: "EMP-005",
    name: "Shifa",
    email: "shifa@workforcehub.com",
    avatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?q=80&w=256&auto=format&fit=crop",
    role: "Sr Executive, HR",
    department: "Human Resources",
    salary: 65000,
    joiningDate: "2024-02-01",
    status: "Active",
    skills: ["Talent Sourcing", "ATS Management", "Employee Engagement"],
    certifications: ["Certified Associate in HR"],
    phone: "+880-1844-556677",
    bloodGroup: "AB+",
    bankAccount: "4455667788990",
    bankName: "Mutual Trust Bank, Uttara Branch",
    tin: "998877112233",
    emergencyContactName: "Md. Harun (Father)",
    emergencyContactPhone: "+880-1922-887766",
    medicalBenefits: "Standard Corporate Health Shield",
    performanceRating: 4,
    leaveBalance: { casual: 14, sick: 13, earned: 10, maternity: 0 },
    promotions: [],
    awards: ["Rising Star Award 2025"],
    disciplinaryActions: []
  },
  {
    id: "EMP-006",
    name: "Arafat Hamim",
    email: "arafat.hamim@workforcehub.com",
    avatar: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?q=80&w=256&auto=format&fit=crop",
    role: "Lead Software Architect",
    department: "Engineering",
    salary: 280000,
    joiningDate: "2021-06-15",
    status: "Active",
    skills: ["System Architecture", "React", "Node.js", "Cloud Ingress", "PostgreSQL"],
    certifications: ["AWS Solutions Architect Pro", "Google Cloud Fellow"],
    phone: "+880-1755-667788",
    bloodGroup: "O+",
    bankAccount: "9876543210987",
    bankName: "Eastern Bank Ltd, Banani Branch",
    tin: "345678912345",
    emergencyContactName: "Rowshan Ara (Mother)",
    emergencyContactPhone: "+880-1766-332211",
    medicalBenefits: "Premium Enterprise Health Insurance",
    performanceRating: 5,
    leaveBalance: { casual: 10, sick: 14, earned: 20, maternity: 0 },
    promotions: [
      { title: "Senior Developer", date: "2021-06-15" },
      { title: "Lead Software Architect", date: "2023-10-01" }
    ],
    awards: ["Innovator of the Year 2024", "Clean Code Master 2025"],
    disciplinaryActions: []
  },
  {
    id: "EMP-007",
    name: "Md. Maksudur",
    email: "md.maksudur@workforcehub.com",
    avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?q=80&w=256&auto=format&fit=crop",
    role: "Department Head, Engineering",
    department: "Engineering",
    salary: 310000,
    joiningDate: "2020-08-01",
    status: "Active",
    skills: ["Engineering Management", "Scaling Systems", "SaaS Infrastructure", "Agile Leadership"],
    certifications: ["PMP", "Certified Scrum Master"],
    phone: "+880-1766-778899",
    bloodGroup: "A+",
    bankAccount: "5678901234567",
    bankName: "Standard Chartered Bank, Gulshan Branch",
    tin: "678901234567",
    emergencyContactName: "Laila Khan (Spouse)",
    emergencyContactPhone: "+880-1833-112233",
    medicalBenefits: "Premium Enterprise Health Insurance",
    performanceRating: 5,
    leaveBalance: { casual: 11, sick: 10, earned: 22, maternity: 0 },
    promotions: [{ title: "Department Head, Engineering", date: "2020-08-01" }],
    awards: ["Elite Leadership Award 2024"],
    disciplinaryActions: []
  },
  {
    id: "EMP-008",
    name: "Shahariar",
    email: "shahariar@workforcehub.com",
    avatar: "https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?q=80&w=256&auto=format&fit=crop",
    role: "UI/UX Lead Designer",
    department: "Product & Design",
    salary: 135000,
    joiningDate: "2022-02-10",
    status: "Active",
    skills: ["Figma", "Design Systems", "Glassmorphism", "Micro-interactions", "Tailwind CSS"],
    certifications: ["Nielsen Norman UX Certified"],
    phone: "+880-1777-889900",
    bloodGroup: "B+",
    bankAccount: "3322114455662",
    bankName: "Brac Bank, Gulshan 1 Branch",
    tin: "778899445566",
    emergencyContactName: "Kamal Hasan (Father)",
    emergencyContactPhone: "+880-1655-443322",
    medicalBenefits: "Standard Corporate Health Shield",
    performanceRating: 4,
    leaveBalance: { casual: 8, sick: 12, earned: 15, maternity: 0 },
    promotions: [{ title: "UI/UX Lead Designer", date: "2024-01-01" }],
    awards: ["Best Interface Designer Award 2024"],
    disciplinaryActions: []
  },
  {
    id: "EMP-009",
    name: "Muntakim",
    email: "muntakim@workforcehub.com",
    avatar: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?q=80&w=256&auto=format&fit=crop",
    role: "Full Stack Lead Developer",
    department: "Engineering",
    salary: 160000,
    joiningDate: "2022-09-01",
    status: "Active",
    skills: ["Next.js", "Express", "PostgreSQL", "Tailwind 4", "TypeScript"],
    certifications: ["Meta Front-End Developer Pro"],
    phone: "+880-1788-990011",
    bloodGroup: "AB+",
    bankAccount: "8877665544321",
    bankName: "City Bank, Mohakhali Branch",
    tin: "889900112233",
    emergencyContactName: "Sultana Razia (Mother)",
    emergencyContactPhone: "+880-1866-998877",
    medicalBenefits: "Standard Corporate Health Shield",
    performanceRating: 5,
    leaveBalance: { casual: 10, sick: 10, earned: 16, maternity: 0 },
    promotions: [{ title: "Full Stack Lead Developer", date: "2024-07-01" }],
    awards: ["Stellar Developer Award Q2 2025"],
    disciplinaryActions: []
  },
  {
    id: "EMP-010",
    name: "Abu Jafor Bipul",
    email: "bipul@workforcehub.com",
    avatar: "https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?q=80&w=256&auto=format&fit=crop",
    role: "Technical Project Manager",
    department: "Engineering",
    salary: 155000,
    joiningDate: "2022-01-20",
    status: "Active",
    skills: ["Agile Management", "SLA Tracking", "Resource Planning", "Risk Mitigation"],
    certifications: ["PMI-ACP", "PRINCE2 Practitioner"],
    phone: "+880-1799-001122",
    bloodGroup: "O+",
    bankAccount: "1234567891012",
    bankName: "Prime Bank, Karwan Bazar Branch",
    tin: "554433778899",
    emergencyContactName: "Anisur Rahman (Father)",
    emergencyContactPhone: "+880-1722-556677",
    medicalBenefits: "Standard Corporate Health Shield",
    performanceRating: 4,
    leaveBalance: { casual: 12, sick: 10, earned: 14, maternity: 0 },
    promotions: [],
    awards: ["Execution Excellence Award 2024"],
    disciplinaryActions: []
  },
  {
    id: "EMP-011",
    name: "Shamsul Huda",
    email: "shamsul.huda@workforcehub.com",
    avatar: "https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?q=80&w=256&auto=format&fit=crop",
    role: "Finance Director",
    department: "Finance & Accounts",
    salary: 240000,
    joiningDate: "2021-11-01",
    status: "Active",
    skills: ["Corporate Treasury", "Bangladesh Tax Law", "Payroll Budgeting", "Audit Readiness"],
    certifications: ["FCA (Bangladesh)", "CMA"],
    phone: "+880-1712-334455",
    bloodGroup: "A-",
    bankAccount: "9876123445678",
    bankName: "Mutual Trust Bank, Gulshan Branch",
    tin: "456789112233",
    emergencyContactName: "Israt Huda (Spouse)",
    emergencyContactPhone: "+880-1611-443322",
    medicalBenefits: "Premium Enterprise Health Insurance",
    performanceRating: 5,
    leaveBalance: { casual: 14, sick: 14, earned: 21, maternity: 0 },
    promotions: [],
    awards: ["Fiscal Prudence Award 2024"],
    disciplinaryActions: []
  },
  {
    id: "EMP-012",
    name: "Himel Dhar",
    email: "himel.dhar@workforcehub.com",
    avatar: "https://images.unsplash.com/photo-1501196354995-cbb51c65aaea?q=80&w=256&auto=format&fit=crop",
    role: "DevOps Engineer",
    department: "Engineering",
    salary: 110000,
    joiningDate: "2023-04-10",
    status: "Active",
    skills: ["Docker", "Kubernetes", "Nginx Reverse Proxy", "CI/CD Pipeling", "Cloud Run"],
    certifications: ["Certified Kubernetes Administrator (CKA)"],
    phone: "+880-1715-998877",
    bloodGroup: "B+",
    bankAccount: "4536271829384",
    bankName: "Eastern Bank Ltd, Mohakhali Branch",
    tin: "231498756345",
    emergencyContactName: "Rita Dhar (Mother)",
    emergencyContactPhone: "+880-1933-778899",
    medicalBenefits: "Standard Corporate Health Shield",
    performanceRating: 4,
    leaveBalance: { casual: 10, sick: 11, earned: 13, maternity: 0 },
    promotions: [],
    awards: ["System Reliability Champion 2025"],
    disciplinaryActions: []
  },
  {
    id: "EMP-013",
    name: "Kazi Abu Bakar",
    email: "bakar@workforcehub.com",
    avatar: "https://images.unsplash.com/photo-1489980508314-941910ded1f4?q=80&w=256&auto=format&fit=crop",
    role: "Cyber Security Architect",
    department: "Engineering",
    salary: 175000,
    joiningDate: "2022-07-01",
    status: "Active",
    skills: ["Penetration Testing", "OAuth 2.0 Security", "JWT Safeguards", "GDPR & Law Compliance"],
    certifications: ["CISSP", "CEH"],
    phone: "+880-1718-445566",
    bloodGroup: "AB-",
    bankAccount: "7766554433221",
    bankName: "Dhaka Bank, Uttara Branch",
    tin: "349018273645",
    emergencyContactName: "Farid Kazi (Father)",
    emergencyContactPhone: "+880-1722-114477",
    medicalBenefits: "Standard Corporate Health Shield",
    performanceRating: 5,
    leaveBalance: { casual: 10, sick: 12, earned: 16, maternity: 0 },
    promotions: [],
    awards: ["Secured Enterprise Award 2024"],
    disciplinaryActions: []
  },
  {
    id: "EMP-014",
    name: "Md. Ashraful",
    email: "ashraful@workforcehub.com",
    avatar: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?q=80&w=256&auto=format&fit=crop",
    role: "QA Manager",
    department: "Engineering",
    salary: 115000,
    joiningDate: "2022-10-15",
    status: "Active",
    skills: ["Automation Testing", "Selenium", "API Testing", "SLA Verification"],
    certifications: ["ISTQB Advanced Level Manager"],
    phone: "+880-1720-112233",
    bloodGroup: "O-",
    bankAccount: "1122998877665",
    bankName: "Brac Bank, Banani Branch",
    tin: "998811224455",
    emergencyContactName: "Nasreen Begum (Mother)",
    emergencyContactPhone: "+880-1811-990011",
    medicalBenefits: "Standard Corporate Health Shield",
    performanceRating: 4,
    leaveBalance: { casual: 8, sick: 12, earned: 14, maternity: 0 },
    promotions: [],
    awards: ["Zero Defect Delivery Award Q3 2025"],
    disciplinaryActions: []
  },
  {
    id: "EMP-015",
    name: "Abdullah Al Mamun",
    email: "mamun@workforcehub.com",
    avatar: "https://images.unsplash.com/photo-1542909168-82c3e7fdca5c?q=80&w=256&auto=format&fit=crop",
    role: "Legal Lead & Labour Advisor",
    department: "Compliance & Legal",
    salary: 180000,
    joiningDate: "2021-04-01",
    status: "Active",
    skills: ["Bangladesh Labour Act 2006", "Contract Negotiation", "Arbitration", "IP Law"],
    certifications: ["Bar-at-Law (Lincoln's Inn)", "Labour Court Advocate Advocate"],
    phone: "+880-1725-556677",
    bloodGroup: "A+",
    bankAccount: "2233445566778",
    bankName: "Prime Bank, Gulshan Branch",
    tin: "556611227788",
    emergencyContactName: "Advocate Fazlul Haque (Father)",
    emergencyContactPhone: "+880-1711-229911",
    medicalBenefits: "Premium Enterprise Health Insurance",
    performanceRating: 5,
    leaveBalance: { casual: 12, sick: 10, earned: 20, maternity: 0 },
    promotions: [],
    awards: ["Best Compliance Advisor 2024"],
    disciplinaryActions: []
  },
  {
    id: "EMP-016",
    name: "Honour Chakma",
    email: "honour.chakma@workforcehub.com",
    avatar: "https://images.unsplash.com/photo-1527980965255-d3b416303d12?q=80&w=256&auto=format&fit=crop",
    role: "Branch HR Manager (Chittagong)",
    department: "Human Resources",
    salary: 110000,
    joiningDate: "2022-08-15",
    status: "Active",
    skills: ["Branch Operations", "Industrial Relations", "Local Compliance", "Dispute Resolution"],
    certifications: ["PGD-HRM (IAB)"],
    phone: "+880-1730-998877",
    bloodGroup: "O+",
    bankAccount: "6677889900112",
    bankName: "City Bank, Agrabad Branch",
    tin: "887711992233",
    emergencyContactName: "Subrata Chakma (Brother)",
    emergencyContactPhone: "+880-1554-112233",
    medicalBenefits: "Standard Corporate Health Shield",
    performanceRating: 4,
    leaveBalance: { casual: 10, sick: 12, earned: 15, maternity: 0 },
    promotions: [],
    awards: ["Regional Harmony Award 2024"],
    disciplinaryActions: []
  },
  {
    id: "EMP-017",
    name: "Sagor Ghosh",
    email: "sagor.ghosh@workforcehub.com",
    avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?q=80&w=256&auto=format&fit=crop",
    role: "Compliance Officer",
    department: "Compliance & Legal",
    salary: 75000,
    joiningDate: "2023-09-01",
    status: "Active",
    skills: ["Bangladesh Labour Law Audit", "Working Hours Tracking", "Overtime Audit"],
    certifications: ["Lead ISO 45001 Auditor"],
    phone: "+880-1735-112233",
    bloodGroup: "B+",
    bankAccount: "5544221199887",
    bankName: "Dutch-Bangla Bank, Mohakhali Branch",
    tin: "334411998822",
    emergencyContactName: "Pradip Ghosh (Father)",
    emergencyContactPhone: "+880-1912-776655",
    medicalBenefits: "Standard Corporate Health Shield",
    performanceRating: 4,
    leaveBalance: { casual: 14, sick: 14, earned: 10, maternity: 0 },
    promotions: [],
    awards: ["Rigorous Auditor Distinction 2025"],
    disciplinaryActions: []
  },
  {
    id: "EMP-018",
    name: "Ahtesam Ul Haque",
    email: "ahtesam@workforcehub.com",
    avatar: "https://images.unsplash.com/photo-1519345182560-3f2917c472ef?q=80&w=256&auto=format&fit=crop",
    role: "Team Lead Developer",
    department: "Engineering",
    salary: 145000,
    joiningDate: "2022-03-01",
    status: "Active",
    skills: ["React Architecture", "TypeScript", "State Orchestration", "Microfrontends"],
    certifications: ["Professional Scrum Master I"],
    phone: "+880-1740-112233",
    bloodGroup: "O+",
    bankAccount: "9900112233445",
    bankName: "Brac Bank, Gulshan 2 Branch",
    tin: "112233448899",
    emergencyContactName: "Dr. Fazlul Haque (Father)",
    emergencyContactPhone: "+880-1715-443322",
    medicalBenefits: "Standard Corporate Health Shield",
    performanceRating: 5,
    leaveBalance: { casual: 10, sick: 11, earned: 17, maternity: 0 },
    promotions: [{ title: "Team Lead Developer", date: "2024-03-01" }],
    awards: ["Best Coach / Mentor Award 2024"],
    disciplinaryActions: []
  },
  {
    id: "EMP-019",
    name: "Maruf",
    email: "maruf@workforcehub.com",
    avatar: "https://images.unsplash.com/photo-1522307837370-cc113a36b784?q=80&w=256&auto=format&fit=crop",
    role: "Digital Marketing Lead",
    department: "Marketing & Communication",
    salary: 85000,
    joiningDate: "2023-11-15",
    status: "Active",
    skills: ["SEO Strategy", "Google Workspace Analytics", "Brand Management", "PR Outreach"],
    certifications: ["Google Analytics Individual Qualification"],
    phone: "+880-1745-112233",
    bloodGroup: "A+",
    bankAccount: "1231231234567",
    bankName: "City Bank, Gulshan Avenue Branch",
    tin: "112255449988",
    emergencyContactName: "Amena Begum (Mother)",
    emergencyContactPhone: "+880-1811-332211",
    medicalBenefits: "Standard Corporate Health Shield",
    performanceRating: 4,
    leaveBalance: { casual: 12, sick: 12, earned: 8, maternity: 0 },
    promotions: [],
    awards: ["Viral Campaign Award 2025"],
    disciplinaryActions: []
  },
  {
    id: "EMP-020",
    name: "Tanvir",
    email: "tanvir@workforcehub.com",
    avatar: "https://images.unsplash.com/photo-1531427186611-ecfd6d936c79?q=80&w=256&auto=format&fit=crop",
    role: "Systems Analyst",
    department: "Engineering",
    salary: 95000,
    joiningDate: "2023-05-10",
    status: "Active",
    skills: ["UML Designs", "System Requirements Mapping", "Enterprise Integrations"],
    certifications: ["CBAP (Certified Business Analysis Professional)"],
    phone: "+880-1750-112233",
    bloodGroup: "O+",
    bankAccount: "9988771122441",
    bankName: "Standard Chartered Bank, Kawran Bazar Branch",
    tin: "445588772211",
    emergencyContactName: "Lutfor Rahman (Father)",
    emergencyContactPhone: "+880-1712-445566",
    medicalBenefits: "Standard Corporate Health Shield",
    performanceRating: 4,
    leaveBalance: { casual: 9, sick: 11, earned: 11, maternity: 0 },
    promotions: [],
    awards: [],
    disciplinaryActions: []
  },
  {
    id: "EMP-021",
    name: "Md. Mehedi Hasan",
    email: "mehedi.hasan@workforcehub.com",
    avatar: "https://images.unsplash.com/photo-1500048993953-d23a436266cf?q=80&w=256&auto=format&fit=crop",
    role: "Network Administrator",
    department: "IT Infrastructure",
    salary: 80000,
    joiningDate: "2023-08-01",
    status: "Active",
    skills: ["Cisco Switches", "VPN Tunnels", "Enterprise Firewall", "WLAN Layouts"],
    certifications: ["CCNA", "CCNP Security"],
    phone: "+880-1755-112233",
    bloodGroup: "B-",
    bankAccount: "5566774433221",
    bankName: "Mutual Trust Bank, Banani Branch",
    tin: "889922113344",
    emergencyContactName: "Hafizur Rahman (Father)",
    emergencyContactPhone: "+880-1552-443355",
    medicalBenefits: "Standard Corporate Health Shield",
    performanceRating: 4,
    leaveBalance: { casual: 14, sick: 10, earned: 9, maternity: 0 },
    promotions: [],
    awards: ["Uptime Guardian Award 2024"],
    disciplinaryActions: []
  },
  {
    id: "EMP-022",
    name: "MD. Shah Sultan",
    email: "shah.sultan@workforcehub.com",
    avatar: "https://images.unsplash.com/photo-1542178243-fcb159518574?q=80&w=256&auto=format&fit=crop",
    role: "SAP Administrator",
    department: "IT Infrastructure",
    salary: 165000,
    joiningDate: "2022-04-15",
    status: "Active",
    skills: ["SAP Basis", "SuccessFactors Integration", "Database Migrations", "ABAP Debugging"],
    certifications: ["SAP Certified Technology Associate"],
    phone: "+880-1760-112233",
    bloodGroup: "A+",
    bankAccount: "7766112299885",
    bankName: "Prime Bank, Mohakhali Branch",
    tin: "332211448899",
    emergencyContactName: "Siddiqur Rahman (Father)",
    emergencyContactPhone: "+880-1911-556677",
    medicalBenefits: "Standard Corporate Health Shield",
    performanceRating: 5,
    leaveBalance: { casual: 10, sick: 12, earned: 15, maternity: 0 },
    promotions: [],
    awards: ["SAP Integration Excellence Award 2024"],
    disciplinaryActions: []
  },
  {
    id: "EMP-023",
    name: "Apu Ahmed",
    email: "apu.ahmed@workforcehub.com",
    avatar: "https://images.unsplash.com/photo-1556157382-97eda2d62296?q=80&w=256&auto=format&fit=crop",
    role: "Payroll Specialist",
    department: "Finance & Accounts",
    salary: 70000,
    joiningDate: "2023-10-01",
    status: "Active",
    skills: ["Salary Structuring", "Income Tax Deductions", "BDT Payroll Runs", "Bank Export Formats"],
    certifications: ["Certified Payroll Professional (CPP)"],
    phone: "+880-1765-112233",
    bloodGroup: "O+",
    bankAccount: "1122334411223",
    bankName: "City Bank, Kawran Bazar Branch",
    tin: "776655112233",
    emergencyContactName: "Rokeya Ahmed (Mother)",
    emergencyContactPhone: "+880-1822-665544",
    medicalBenefits: "Standard Corporate Health Shield",
    performanceRating: 4,
    leaveBalance: { casual: 14, sick: 11, earned: 8, maternity: 0 },
    promotions: [],
    awards: ["Pristine Ledger Distinction 2025"],
    disciplinaryActions: []
  },
  {
    id: "EMP-024",
    name: "Nishat Tasnim",
    email: "nishat.tasnim@workforcehub.com",
    avatar: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?q=80&w=256&auto=format&fit=crop",
    role: "L&D Coordinator",
    department: "Human Resources",
    salary: 68000,
    joiningDate: "2024-01-10",
    status: "Active",
    skills: ["Curriculum Engineering", "Skill Matrix Analytics", "LMS Administration"],
    certifications: ["ATD Certified Professional in Talent Development"],
    phone: "+880-1770-112233",
    bloodGroup: "B+",
    bankAccount: "9988334455661",
    bankName: "Dutch-Bangla Bank, Mohakhali Branch",
    tin: "554499112233",
    emergencyContactName: "Dr. Nazma Tasnim (Sister)",
    emergencyContactPhone: "+880-1711-558822",
    medicalBenefits: "Standard Corporate Health Shield",
    performanceRating: 4,
    leaveBalance: { casual: 14, sick: 14, earned: 10, maternity: 112 },
    promotions: [],
    awards: ["Elearning Trailblazer Award 2024"],
    disciplinaryActions: []
  },
  {
    id: "EMP-025",
    name: "Masud Rana",
    email: "masud.rana@workforcehub.com",
    avatar: "https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?q=80&w=256&auto=format&fit=crop",
    role: "Operations Manager",
    department: "Operations",
    salary: 120000,
    joiningDate: "2021-10-01",
    status: "Active",
    skills: ["Supply Chain Logistics", "Facilities Oversight", "SLA Audits", "Procurement Management"],
    certifications: ["CSCP (Supply Chain Pro)"],
    phone: "+880-1775-112233",
    bloodGroup: "O+",
    bankAccount: "4433221155662",
    bankName: "Eastern Bank Ltd, Banani Branch",
    tin: "667722119988",
    emergencyContactName: "Hamida Begum (Spouse)",
    emergencyContactPhone: "+880-1612-998877",
    medicalBenefits: "Standard Corporate Health Shield",
    performanceRating: 4,
    leaveBalance: { casual: 10, sick: 12, earned: 18, maternity: 0 },
    promotions: [],
    awards: ["Operational Efficiency Distinction 2024"],
    disciplinaryActions: []
  },
  {
    id: "EMP-026",
    name: "Amit Hasan",
    email: "amit.hasan@workforcehub.com",
    avatar: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?q=80&w=256&auto=format&fit=crop",
    role: "Technical Support Specialist",
    department: "IT Infrastructure",
    salary: 55000,
    joiningDate: "2024-03-01",
    status: "Active",
    skills: ["Hardware Overhaul", "Active Directory Administration", "Network Debugging"],
    certifications: ["CompTIA A+", "Network+"],
    phone: "+880-1780-112233",
    bloodGroup: "A+",
    bankAccount: "1122445522110",
    bankName: "Brac Bank, Gulshan 1 Branch",
    tin: "443322998811",
    emergencyContactName: "Abul Hasan (Father)",
    emergencyContactPhone: "+880-1811-554433",
    medicalBenefits: "Standard Corporate Health Shield",
    performanceRating: 4,
    leaveBalance: { casual: 14, sick: 14, earned: 6, maternity: 0 },
    promotions: [],
    awards: ["Customer Service Excellence 2025"],
    disciplinaryActions: []
  },
  {
    id: "EMP-027",
    name: "Molla Badhon",
    email: "molla.badhon@workforcehub.com",
    avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=256&auto=format&fit=crop",
    role: "Intern, Frontend",
    department: "Engineering",
    salary: 25000,
    joiningDate: "2026-04-01",
    status: "Probation",
    skills: ["React Basics", "CSS Glassmorphism", "HTML & Tailwind"],
    certifications: [],
    phone: "+880-1785-112233",
    bloodGroup: "B+",
    bankAccount: "9988112233441",
    bankName: "City Bank, Mohakhali Branch",
    tin: "998811223344",
    emergencyContactName: "Rafiqul Islam Molla (Father)",
    emergencyContactPhone: "+880-1755-998822",
    medicalBenefits: "Basic Accident Coverage",
    performanceRating: 4,
    leaveBalance: { casual: 5, sick: 5, earned: 0, maternity: 0 },
    promotions: [],
    awards: [],
    disciplinaryActions: []
  },
  {
    id: "EMP-028",
    name: "Nasib Ul Awal",
    email: "nasib@workforcehub.com",
    avatar: "https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?q=80&w=256&auto=format&fit=crop",
    role: "Senior Software Engineer",
    department: "Engineering",
    salary: 130000,
    joiningDate: "2022-11-01",
    status: "Active",
    skills: ["Microservices", "PostgreSQL tuning", "GraphQL APIs", "Caching Strategy"],
    certifications: ["Oracle Certified Professional Java EE"],
    phone: "+880-1790-112233",
    bloodGroup: "O+",
    bankAccount: "1122335544667",
    bankName: "Dutch-Bangla Bank, Mohakhali Branch",
    tin: "223344119900",
    emergencyContactName: "Shirin Awal (Mother)",
    emergencyContactPhone: "+880-1922-334455",
    medicalBenefits: "Standard Corporate Health Shield",
    performanceRating: 5,
    leaveBalance: { casual: 10, sick: 11, earned: 15, maternity: 0 },
    promotions: [],
    awards: ["Backend Wizard Award 2024"],
    disciplinaryActions: []
  },
  {
    id: "EMP-029",
    name: "Sheikh Sifat",
    email: "sifat@workforcehub.com",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=256&auto=format&fit=crop",
    role: "Lead Data Scientist",
    department: "Engineering",
    salary: 170000,
    joiningDate: "2023-01-20",
    status: "Active",
    skills: ["Predictive Modelling", "LLM Fine-tuning", "Workforce Forecasting Algorithms", "Python Data Stack"],
    certifications: ["Google Cloud Certified Professional Data Engineer"],
    phone: "+880-1795-112233",
    bloodGroup: "A+",
    bankAccount: "5566771122334",
    bankName: "HSBC Bangladesh, Banani Branch",
    tin: "889911224455",
    emergencyContactName: "Sheikh Abdul Khaleque (Father)",
    emergencyContactPhone: "+880-1611-334466",
    medicalBenefits: "Standard Corporate Health Shield",
    performanceRating: 5,
    leaveBalance: { casual: 10, sick: 12, earned: 13, maternity: 0 },
    promotions: [],
    awards: ["AI Implementation Excellence Award 2024"],
    disciplinaryActions: []
  },
  {
    id: "EMP-030",
    name: "Shakhawat",
    email: "shakhawat@workforcehub.com",
    avatar: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?q=80&w=256&auto=format&fit=crop",
    role: "Database Administrator",
    department: "Engineering",
    salary: 105000,
    joiningDate: "2023-02-15",
    status: "Active",
    skills: ["Database Replication", "High Availability Clusters", "Drizzle & Prisma Configurations", "Query Optimization"],
    certifications: ["Oracle Database Administration Specialist"],
    phone: "+880-1711-223344",
    bloodGroup: "O+",
    bankAccount: "9988771122332",
    bankName: "City Bank, Kawran Bazar Branch",
    tin: "334422119988",
    emergencyContactName: "Fatema Begum (Mother)",
    emergencyContactPhone: "+880-1811-998877",
    medicalBenefits: "Standard Corporate Health Shield",
    performanceRating: 4,
    leaveBalance: { casual: 11, sick: 11, earned: 12, maternity: 0 },
    promotions: [],
    awards: [],
    disciplinaryActions: []
  },
  {
    id: "EMP-031",
    name: "Hasibul Hasan",
    email: "hasibul.hasan@workforcehub.com",
    avatar: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?q=80&w=256&auto=format&fit=crop",
    role: "Talent Acquisition Coordinator",
    department: "Human Resources",
    salary: 62000,
    joiningDate: "2024-05-01",
    status: "Active",
    skills: ["Talent Pools Sourcing", "Interview Coordination", "Offer Operations"],
    certifications: ["AIRS Certified Recruiter"],
    phone: "+880-1722-334455",
    bloodGroup: "B+",
    bankAccount: "1122334455661",
    bankName: "Brac Bank, Banani Branch",
    tin: "990011223344",
    emergencyContactName: "Nazrul Islam (Father)",
    emergencyContactPhone: "+880-1922-334455",
    medicalBenefits: "Standard Corporate Health Shield",
    performanceRating: 4,
    leaveBalance: { casual: 14, sick: 14, earned: 4, maternity: 0 },
    promotions: [],
    awards: [],
    disciplinaryActions: []
  },
  {
    id: "EMP-032",
    name: "Sayman Mehedi",
    email: "sayman.mehedi@workforcehub.com",
    avatar: "https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?q=80&w=256&auto=format&fit=crop",
    role: "Product Owner (HCM Core)",
    department: "Product & Design",
    salary: 130000,
    joiningDate: "2023-01-10",
    status: "Active",
    skills: ["Product Roadmap Engineering", "User Story Mapping", "Enterprise Workflows Architecture"],
    certifications: ["Professional Scrum Product Owner (PSPO I)"],
    phone: "+880-1733-445566",
    bloodGroup: "O+",
    bankAccount: "5544332211992",
    bankName: "Prime Bank, Gulshan Branch",
    tin: "223344889911",
    emergencyContactName: "Mehedi Hasan Sr. (Father)",
    emergencyContactPhone: "+880-1711-334455",
    medicalBenefits: "Standard Corporate Health Shield",
    performanceRating: 5,
    leaveBalance: { casual: 10, sick: 12, earned: 14, maternity: 0 },
    promotions: [],
    awards: ["Exemplary Visionary Award 2024"],
    disciplinaryActions: []
  },
  {
    id: "EMP-033",
    name: "Sobuj",
    email: "sobuj@workforcehub.com",
    avatar: "https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?q=80&w=256&auto=format&fit=crop",
    role: "Mobile Developer",
    department: "Engineering",
    salary: 85000,
    joiningDate: "2024-02-15",
    status: "Active",
    skills: ["React Native", "Android Core API", "iOS SDK Configurations"],
    certifications: ["Meta Certified iOS Developer"],
    phone: "+880-1744-556677",
    bloodGroup: "A+",
    bankAccount: "9988776655441",
    bankName: "Dutch-Bangla Bank, Mohakhali Branch",
    tin: "554433112233",
    emergencyContactName: "Zakir Hossain (Father)",
    emergencyContactPhone: "+880-1933-445566",
    medicalBenefits: "Standard Corporate Health Shield",
    performanceRating: 4,
    leaveBalance: { casual: 14, sick: 12, earned: 8, maternity: 0 },
    promotions: [],
    awards: [],
    disciplinaryActions: []
  },
  {
    id: "EMP-034",
    name: "R. A. Shah Sultan",
    email: "ra.shah@workforcehub.com",
    avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?q=80&w=256&auto=format&fit=crop",
    role: "Executive, Procurement",
    department: "Operations",
    salary: 62000,
    joiningDate: "2024-06-01",
    status: "Active",
    skills: ["Vendor Relations", "Capex Budget Tracking", "Material Audits"],
    certifications: ["CIPS Diploma (Procurement)"],
    phone: "+880-1755-667788",
    bloodGroup: "O+",
    bankAccount: "1122334499881",
    bankName: "Standard Chartered Bank, Gulshan Branch",
    tin: "889911223344",
    emergencyContactName: "Sultan Ahmed (Father)",
    emergencyContactPhone: "+880-1811-667788",
    medicalBenefits: "Standard Corporate Health Shield",
    performanceRating: 4,
    leaveBalance: { casual: 14, sick: 14, earned: 3, maternity: 0 },
    promotions: [],
    awards: [],
    disciplinaryActions: []
  },
  {
    id: "EMP-035",
    name: "Sahriar",
    email: "sahriar.ba@workforcehub.com",
    avatar: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?q=80&w=256&auto=format&fit=crop",
    role: "Business Analyst",
    department: "Operations",
    salary: 78000,
    joiningDate: "2024-01-15",
    status: "Active",
    skills: ["BPMN Workflows", "Business Analytics", "ROI Analysis"],
    certifications: ["ECBA Certified"],
    phone: "+880-1766-778899",
    bloodGroup: "B+",
    bankAccount: "5566778811223",
    bankName: "City Bank, Kawran Bazar Branch",
    tin: "443311229988",
    emergencyContactName: "Farid Uddin (Father)",
    emergencyContactPhone: "+880-1922-887766",
    medicalBenefits: "Standard Corporate Health Shield",
    performanceRating: 4,
    leaveBalance: { casual: 12, sick: 12, earned: 10, maternity: 0 },
    promotions: [],
    awards: [],
    disciplinaryActions: []
  },
  {
    id: "EMP-036",
    name: "Dipto",
    email: "dipto@workforcehub.com",
    avatar: "https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?q=80&w=256&auto=format&fit=crop",
    role: "UI/UX Designer",
    department: "Product & Design",
    salary: 80000,
    joiningDate: "2024-03-10",
    status: "Active",
    skills: ["Vector Graphics", "Interaction Prototyping", "Design Systems"],
    certifications: ["Google UX Design Certificate"],
    phone: "+880-1777-889911",
    bloodGroup: "O+",
    bankAccount: "9900112233446",
    bankName: "Brac Bank, Gulshan 1 Branch",
    tin: "112233445588",
    emergencyContactName: "Bishwajit Ghosh (Father)",
    emergencyContactPhone: "+880-1944-556677",
    medicalBenefits: "Standard Corporate Health Shield",
    performanceRating: 4,
    leaveBalance: { casual: 14, sick: 14, earned: 6, maternity: 0 },
    promotions: [],
    awards: [],
    disciplinaryActions: []
  },
  {
    id: "EMP-037",
    name: "Kawsar Ahmed",
    email: "kawsar@workforcehub.com",
    avatar: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?q=80&w=256&auto=format&fit=crop",
    role: "Backend Developer",
    department: "Engineering",
    salary: 82000,
    joiningDate: "2024-02-01",
    status: "Active",
    skills: ["Node.js", "Express routing", "SQL database design", "Redis cache"],
    certifications: ["MERN Stack Pro Certificate"],
    phone: "+880-1788-991122",
    bloodGroup: "A+",
    bankAccount: "2233445511224",
    bankName: "Mutual Trust Bank, Uttara Branch",
    tin: "889922114433",
    emergencyContactName: "Ataur Rahman (Father)",
    emergencyContactPhone: "+880-1955-667788",
    medicalBenefits: "Standard Corporate Health Shield",
    performanceRating: 4,
    leaveBalance: { casual: 14, sick: 12, earned: 8, maternity: 0 },
    promotions: [],
    awards: [],
    disciplinaryActions: []
  },
  {
    id: "EMP-038",
    name: "MD. Fuad Hasan",
    email: "fuad.hasan@workforcehub.com",
    avatar: "https://images.unsplash.com/photo-1542909168-82c3e7fdca5c?q=80&w=256&auto=format&fit=crop",
    role: "HR Generalist",
    department: "Human Resources",
    salary: 58000,
    joiningDate: "2024-07-01",
    status: "Active",
    skills: ["HR Operations", "Handbook Editing", "Bangladesh Legal Audits"],
    certifications: ["Professional HR Associate Certificate"],
    phone: "+880-1799-223344",
    bloodGroup: "O+",
    bankAccount: "5566771122449",
    bankName: "City Bank, Mohakhali Branch",
    tin: "556622119900",
    emergencyContactName: "Rehana Hasan (Mother)",
    emergencyContactPhone: "+880-1811-223344",
    medicalBenefits: "Standard Corporate Health Shield",
    performanceRating: 4,
    leaveBalance: { casual: 14, sick: 14, earned: 1, maternity: 0 },
    promotions: [],
    awards: [],
    disciplinaryActions: []
  },
  {
    id: "EMP-039",
    name: "Imtiyaz Al Mahmood",
    email: "imtiyaz@workforcehub.com",
    avatar: "https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?q=80&w=256&auto=format&fit=crop",
    role: "Brand Strategist",
    department: "Marketing & Communication",
    salary: 92000,
    joiningDate: "2023-06-15",
    status: "Active",
    skills: ["Brand Strategy", "PR Campaigns", "Copywriting", "Exposition Marketing"],
    certifications: ["Professional Certified Marketer (PCM)"],
    phone: "+880-1711-334466",
    bloodGroup: "B+",
    bankAccount: "1122998844331",
    bankName: "Brac Bank, Banani Branch",
    tin: "998811225566",
    emergencyContactName: "Mahmood Alam (Father)",
    emergencyContactPhone: "+880-1611-998877",
    medicalBenefits: "Standard Corporate Health Shield",
    performanceRating: 4,
    leaveBalance: { casual: 10, sick: 11, earned: 14, maternity: 0 },
    promotions: [],
    awards: ["Creative Genius Award Q4 2024"],
    disciplinaryActions: []
  },
  {
    id: "EMP-040",
    name: "Faroque",
    email: "faroque@workforcehub.com",
    avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?q=80&w=256&auto=format&fit=crop",
    role: "Logistics Lead",
    department: "Operations",
    salary: 82000,
    joiningDate: "2023-02-01",
    status: "Active",
    skills: ["Dispatch Scheduling", "Vehicle Management", "Bangladesh Road Act Compliance"],
    certifications: ["Certified Supply Chain Specialist"],
    phone: "+880-1722-445577",
    bloodGroup: "O+",
    bankAccount: "4433112255669",
    bankName: "HSBC Bangladesh, Agrabad Branch",
    tin: "443322119900",
    emergencyContactName: "Amena Faroque (Spouse)",
    emergencyContactPhone: "+880-1811-445566",
    medicalBenefits: "Standard Corporate Health Shield",
    performanceRating: 4,
    leaveBalance: { casual: 12, sick: 12, earned: 14, maternity: 0 },
    promotions: [],
    awards: ["Best Logistics Executive Award 2024"],
    disciplinaryActions: []
  },
  {
    id: "EMP-041",
    name: "Mohammad Noman",
    email: "noman@workforcehub.com",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=256&auto=format&fit=crop",
    role: "Facility Specialist",
    department: "Operations",
    salary: 50000,
    joiningDate: "2024-04-10",
    status: "Active",
    skills: ["Power Grid Oversight", "Workplace Safety Codes", "Vendor Maintenance SLA Audits"],
    certifications: ["OSHA General Industry Certified"],
    phone: "+880-1733-556699",
    bloodGroup: "AB+",
    bankAccount: "1122339988771",
    bankName: "Prime Bank, Gulshan Branch",
    tin: "112244998833",
    emergencyContactName: "Abdur Rashid (Father)",
    emergencyContactPhone: "+880-1922-445566",
    medicalBenefits: "Standard Corporate Health Shield",
    performanceRating: 4,
    leaveBalance: { casual: 14, sick: 14, earned: 5, maternity: 0 },
    promotions: [],
    awards: [],
    disciplinaryActions: []
  }
];

export const initialRequisitions: JobRequisition[] = [
  {
    id: "REQ-001",
    title: "Senior React Developer",
    department: "Engineering",
    vacancies: 2,
    status: "Published",
    priority: "High",
    salaryRange: "110,000 - 150,000 BDT",
    postedDate: "2026-06-15",
    applicants: [
      {
        id: "CAN-001",
        name: "Ariful Islam",
        email: "ariful@gmail.com",
        phone: "+880-1711-222333",
        skills: ["React", "TypeScript", "Tailwind CSS", "Redux"],
        experienceYears: 5,
        parsedSummary: "Ariful is an experienced Frontend Engineer with 5 years in building React SPAs and responsive designs. He demonstrated robust problem solving in Tailwind CSS and state management.",
        score: 88,
        status: "Interviewing",
        interviews: [
          { round: "Technical Interview", dateTime: "2026-07-05 10:00 AM", interviewer: "Arafat Hamim", feedback: "Strong technical knowledge of React fiber and optimization.", score: 90 }
        ],
        salaryRecommendation: 130000
      },
      {
        id: "CAN-002",
        name: "Sonia Akter",
        email: "sonia.akter@outlook.com",
        phone: "+880-1812-444555",
        skills: ["React", "JavaScript", "CSS Glassmorphism", "Node.js"],
        experienceYears: 3,
        parsedSummary: "Sonia has a solid 3-year track record in building client dashboards with polished UI/UX details. Understands CSS grids and Tailwind utility frameworks thoroughly.",
        score: 75,
        status: "CV Screened",
        interviews: [],
        salaryRecommendation: 110000
      }
    ]
  },
  {
    id: "REQ-002",
    title: "Cyber Security Specialist",
    department: "Engineering",
    vacancies: 1,
    status: "Approved",
    priority: "Critical",
    salaryRange: "140,000 - 180,000 BDT",
    postedDate: "2026-06-20",
    applicants: [
      {
        id: "CAN-003",
        name: "Tareq Jamil",
        email: "tareq.cyber@gmail.com",
        phone: "+880-1915-777888",
        skills: ["JWT", "OAuth 2.0", "Penetration Testing", "Security Audits"],
        experienceYears: 6,
        parsedSummary: "Tareq possesses comprehensive knowledge in JWT secure cookie configurations, RBAC architectures, and penetration testing on cloud-deployed node systems.",
        score: 94,
        status: "Applied",
        interviews: [],
        salaryRecommendation: 165000
      }
    ]
  }
];

export const initialLeaveRequests: LeaveRequest[] = [
  {
    id: "LR-001",
    employeeId: "EMP-003",
    employeeName: "Suchana",
    department: "Human Resources",
    type: "Casual",
    startDate: "2026-07-04",
    endDate: "2026-07-05",
    days: 2,
    reason: "Personal family event in Sylhet.",
    status: "Pending",
    appliedDate: "2026-07-02"
  },
  {
    id: "LR-002",
    employeeId: "EMP-018",
    employeeName: "Ahtesam Ul Haque",
    department: "Engineering",
    type: "Sick",
    startDate: "2026-06-25",
    endDate: "2026-06-26",
    days: 2,
    reason: "Severe fever and clinical rest.",
    status: "Approved",
    appliedDate: "2026-06-25"
  }
];

export const initialAttendanceRecords: AttendanceRecord[] = [
  { id: "ATT-001", employeeId: "EMP-001", employeeName: "SMI Fahim", department: "Executive Committee", date: "2026-07-03", checkIn: "08:55", checkOut: "18:10", status: "Present", location: "GPS (Dhaka Head Office)", otHours: 0 },
  { id: "ATT-002", employeeId: "EMP-002", employeeName: "Abrar Ishraq", department: "Human Resources", date: "2026-07-03", checkIn: "08:48", checkOut: "18:05", status: "Present", location: "GPS (Dhaka Head Office)", otHours: 0 },
  { id: "ATT-003", employeeId: "EMP-003", employeeName: "Suchana", department: "Human Resources", date: "2026-07-03", checkIn: "09:40", checkOut: "18:00", status: "Late", location: "GPS (Dhaka Head Office)", otHours: 0, lateReason: "Severe traffic gridlock at Mohakhali Flyover." },
  { id: "ATT-004", employeeId: "EMP-006", employeeName: "Arafat Hamim", department: "Engineering", date: "2026-07-03", checkIn: "08:50", checkOut: "19:15", status: "Present", location: "Remote (Work from home)", otHours: 1.25 },
  { id: "ATT-005", employeeId: "EMP-009", employeeName: "Muntakim", department: "Engineering", date: "2026-07-03", checkIn: "08:55", checkOut: "20:00", status: "Present", location: "GPS (Dhaka Head Office)", otHours: 2.0 }
];

export const initialPayrollRuns: PayrollRun[] = [
  { id: "PAY-001", employeeId: "EMP-001", employeeName: "SMI Fahim", department: "Executive Committee", month: "June 2026", basic: 250000, allowance: 150000, overtime: 0, tax: 50000, netPay: 350000, status: "Paid" },
  { id: "PAY-002", employeeId: "EMP-002", employeeName: "Abrar Ishraq", department: "Human Resources", month: "June 2026", basic: 130000, allowance: 60000, overtime: 0, tax: 25000, netPay: 165000, status: "Paid" },
  { id: "PAY-003", employeeId: "EMP-003", employeeName: "Suchana", department: "Human Resources", month: "June 2026", basic: 80000, allowance: 40000, overtime: 0, tax: 10000, netPay: 110000, status: "Paid" },
  { id: "PAY-004", employeeId: "EMP-006", employeeName: "Arafat Hamim", department: "Engineering", month: "June 2026", basic: 170000, allowance: 70000, overtime: 12000, tax: 35000, netPay: 217000, status: "Paid" }
];

export const initialGoals: PerformanceGoal[] = [
  { id: "G-001", employeeId: "EMP-006", employeeName: "Arafat Hamim", title: "Migrate legacy app to scalable Express / Vite full-stack server", category: "OKR", progress: 95, targetDate: "2026-07-15", status: "In Progress" },
  { id: "G-002", employeeId: "EMP-008", employeeName: "Shahariar", title: "Implement comprehensive enterprise micro-interactions & glassmorphism system", category: "KPI", progress: 100, targetDate: "2026-06-30", status: "Completed" },
  { id: "G-003", employeeId: "EMP-009", employeeName: "Muntakim", title: "Develop CV screening parser & AI candidate ranking engine backend integration", category: "OKR", progress: 80, targetDate: "2026-07-10", status: "In Progress" }
];

export const initialCourses: Course[] = [
  { id: "CRS-001", title: "Bangladesh Labour Act 2006 & HR Legal Compliance", provider: "WorkForceHub Compliance Academy", duration: "12 Hours", category: "Legal & Law", enrolledCount: 14, rating: 4.9, coverColor: "from-emerald-500 to-teal-600" },
  { id: "CRS-002", title: "Advanced Enterprise Security, JWT Cookie Safeguards & RBAC", provider: "Bakar Cybersecurity Academy", duration: "8 Hours", category: "Cybersecurity", enrolledCount: 22, rating: 4.8, coverColor: "from-cyan-500 to-blue-600" },
  { id: "CRS-003", title: "High-Performance Node Systems & Vite HMR Optimizations", provider: "Engineering Core Team", duration: "6 Hours", category: "Technical Development", enrolledCount: 18, rating: 4.7, coverColor: "from-green-500 to-emerald-600" }
];

export const initialTickets: SupportTicket[] = [
  { id: "TCK-001", employeeName: "Suchana", category: "Payroll", subject: "Increment cycle mapping in BDT ledger", priority: "High", status: "In Progress", createdAt: "2026-07-02 09:15 AM", description: "The automatic increment engine requires a secondary tax adjustment confirmation step in standard SCB BDT payroll reports." },
  { id: "TCK-002", employeeName: "Ahtesam Ul Haque", category: "IT Support", subject: "Port 3000 reverse proxy routing failure", priority: "High", status: "Resolved", createdAt: "2026-07-01 11:30 AM", description: "HMR was disabled on our sandbox, but manual server bindings should strictly follow 0.0.0.0:3000 to resolve public frame render issues." }
];

export const initialAnnouncements: CompanyAnnouncement[] = [
  { id: "ANN-001", title: "WorkForceHub 3.0 Platform Expansion!", content: "We are thrilled to launch our next-generation HCM core platform designed to rival international offerings from Workday and SuccessFactors, optimized specifically for major enterprises in Bangladesh.", author: "SMI Fahim", authorRole: "CEO & Managing Director", date: "2026-07-03", category: "General" },
  { id: "ANN-002", title: "Full Compliance Compliance Certification!", content: "Our legal legal and labour compliance advisor, Abdullah Al Mamun, has completed the certification audits validating complete platform alignment with the Bangladesh Labour Act amendments.", author: "Abdullah Al Mamun", authorRole: "Legal Lead", date: "2026-07-01", category: "Policy Update" }
];
